[tool.poetry]
name = "python-demos"
version = "0.1.0"
description = ""
authors = ["harden <harden@shundaojia.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
twisted = "^24.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
